### ISSUE TITLE
Optional support

### ISSUE THREAD

**Issue by ben-manes** [h908714124/auto-builder#1]
When migrating, Optional fields are not handled equivalently to Google's builders. They should accept the value directly, but yours requires a wrapper. (There may be other differences, like lists, so you should check against AutoValue's documentation)

Please also document `@AutoBuilder`, as new team members might look at that instead of searching for your github project.

**Comment by h908714124** [comment]
OK cool thanks for the feedback. I'll have a look at optional and list.

**Comment by ben-manes** [comment]
It looks like I use both styles for `Optional` (wrapped and unwrapped). So generating both options would be ideal.

**Comment by h908714124** [comment]
I've released 1.1 with optional support. I wasn't sure how to do list support. Feel free to open another issue, if you need it.
