### ISSUE TITLE
Validation callback

### ISSUE THREAD

**Issue by ben-manes** [h908714124/auto-builder#13]
In a hand written `AutoValue` builder, [validation](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#validate) can be accomplished by using a private `autoBuild()` and processing the `build()` yourself. The generated builder does not have such a nice hook.

Perhaps instead a new annotation could be introduced to execute a callback method when complete. Something like,

```java
@AutoValue @AutoBuilder
public static abstract class UserDetails {
  public abstract String firstName();
  public abstract String lastName();
  public abstract @Nullable String email();
  public abstract @Nullable String phone();

  @AutoBuilder.Validate
  void validate() {
    checkState((email() != null) || (phone() != null), "Email or phone required");
  }
  
  public static UserDetails_Builder builder() {
    return UserCreator_UserDetails_Builder.builder();
  }
}
```

Then the `build()` method would automatically call `validate()` before returning the instance.

**Comment by h908714124** [comment]
A suggestion: #16

**Comment by ben-manes** [comment]
lgtm, thanks!

**Comment by ben-manes** [comment]
I nice aspect of your approach is it supports [normalize modify a property value at build time](https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#-normalize-modify-a-property-value-at-build-time). In your example, one would return a different instance with the modifications, so there's a tiny cost of a temporary allocation, which is fine. This could be avoided by passing the builder into the post build method, but I don't feel strongly one way or the other.

**Comment by h908714124** [comment]
Oops, I think it has to be the builder passed to the method. Otherwise there would be an infinite loop. I will update the PR tomorrow.

**Comment by ben-manes** [comment]
In that case the method must not call `build()` itself or risk an infinite loop. That may not be too bad as fails the first time its run and easy to remember not to do, but allow an easy mistake. I'm sure when you think through it again there will be a clean solution, though.

**Comment by h908714124** [comment]
I will try passing a subclass of the builder, which has a "safe" build method.

**Comment by ben-manes** [comment]
You might also want to take a quick look at [Immutables' check method](https://immutables.github.io/immutable.html#precondition-check-method). I don't use it since they threw in the kitchen sink and prefer Auto's simplicity, but still good reference of ideas.
