### ISSUE TITLE
Using @Memoized causes build failure

### ISSUE THREAD

**Issue by ben-manes** [h908714124/auto-builder#17]
I'm not sure why, as the compile error is not clear, but it fails to generate the Builder when using `@Memoized`. AutoValue generates the value class with a `$` prefix and then extends it for the memoized component. This is somehow confusing `@AutoBuilder`, though again the actual failure is lost in the output. I can use `@Memoized` or `@AutoBuilder` separately without a problem.

**Comment by h908714124** [comment]
Thank you. I will look at this.
