### ISSUE TITLE
Abstract and default methods

### ISSUE THREAD

**Issue by ben-manes** [h908714124/auto-builder#2]
Attempting to migrate to 1.1 shows another difference. I have the following use-case.

```java
interface Source {
  ...
  default ImmutableMap<UUID, Path> files() {
    return ImmutableMap.of();
  }
```

```java
public abstract class RequestSource implements Source {
  ...
  @Override public abstract ImmutableMap<UUID, Path> files();

  @AutoValue.Builder
  abstract static class Builder {
    ...
    public abstract Builder files(Map<UUID, Path> files);
    public abstract RequestSource build();
  }
}
```

In the above I need to provide the files, so I make the method abstract so that a field is generated. In yours, it is tricked by the default and does not generate the field.

**Comment by h908714124** [comment]
Hey Ben, I'm glad you're interested in this project, and I wish I could spend more time on it myself. 
I'm not sure yet what this particular issue is about, though.
The processor uses `AutoValue_RequestSource.java` as input. It doesn't even look at `RequestSource.java` (beyond that fact that it carries `@AutoBuilder`), and doesn't know which methods it has, or which interfaces it's implementing.

I have created a new repo, specifically for this issue and others that may arise in the future: https://github.com/h908714124/auto-builder-issues/
If you could make a pull request there that reproduces the problem (maybe a failing unit test?), that would be fantastic indeed. Cheers!

**Comment by ben-manes** [comment]
I'm sorry, this was my fault. I had thought that I checked the generated sources, but in retrying I see it is a minor issue. The actual failure is that `RequestSource_Builder#files` only accepts an `ImmutableMap` and not the collection interface. Google's will generate a `Map` for convenience.

**Comment by h908714124** [comment]
No problem
